#아이디, 비밀번호 입력

SAMPLE_ID = "1111"
SAMPLE_SECRET = "1111"

#Project21
PROJECT21_EZADMIN_ID = "pista1004"
PROJECT21_EZADMIN_PW = "founders21!"
PROJECT21_EZADMIN_DOMAIN = "pista1004"
PROJECT21_CAFE24_ID = 'project21'
PROJECT21_CAFE24_PW = 'pista1004!!'

PROJECT21_NAVERSHOP_ID = "pista1004"
PROJECT21_NAVERSHOP_PW = "pista1004!"
PROJECT21_NAVERSHOP_TYPE = "general"

#ANUA
ANUA_EZADMIN_ID = "anua"
ANUA_EZADMIN_PW = "founders21!"
ANUA_EZADMIN_DOMAIN = "anua"

ANUA_NAVERSHOP_ID = "anua"
ANUA_NAVERSHOP_PW = "pista1004!"
ANUA_NAVERSHOP_TYPE = "general"

#LAVENA
LAVENA_NAVERSHOP_ID = "lavenakorea"
LAVENA_NAVERSHOP_PW = "lavena21!"
LAVENA_NAVERSHOP_TYPE = "naver"

#YUGE
YUGE_NAVERSHOP_ID = "yuge"
YUGE_NAVERSHOP_PW = "founders21!"
YUGE_NAVERSHOP_TYPE = "general"

